version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopping-cart-api
    ports:
      - "8080:8080"
    restart: always